export default class LiteStoreConstants {
  /* 保存所有LiteStore的键名 */

  // 食物商店: 指定需要上架的食物
  static readonly PHONE_FOOD_STORE_KEY = 'phone_foodStore_key';
  static readonly TABLET_FOOD_STORE_KEY = 'tablet_foodStore_key';
  // 角色信息：健康、饱腹、金币、经验值、好感度
  static readonly CHARACTER_KEY = 'character_key';
  static readonly CHARACTER_LIST_KEY = 'character_list_key'; // 所有角色列表
  // 卫生信息: 手整洁、牙齿整洁
  static readonly HYGIENE_KEY = 'hygiene_key';
  // 背包物品
  static readonly BAG_FOOD_KEY = 'bagFood_key';
}