/*  提供9条列表数据 - 色素饮料01234...  */

//import { FoodData } from '../../feed/model/FoodData';
//
//  export class TestList {
//    foods: Array<FoodData> = [
//      {
//        "foodId": 0,
//        "title": "色素饮料0",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      }, {
//        "foodId": 1,
//        "title": "色素饮料1",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      },
//      {
//        "foodId": 2,
//        "title": "色素饮料2",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      },
//      {
//        "foodId": 3,
//        "title": "色素饮料3",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      },
//      {
//        "foodId": 4,
//        "title": "色素饮料4",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      },
//      {
//        "foodId": 5,
//        "title": "色素饮料5",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      },
//      {
//        "foodId": 6,
//        "title": "色素饮料6",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      },
//      {
//        "foodId": 7,
//        "title": "色素饮料7",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      },
//      {
//        "foodId": 8,
//        "title": "色素饮料8",
//        "type": "drink",
//        "hunger": 10,
//        "health": -1,
//        "introduction": "色素饮料有丰富的颜色，通常勾兑了添加剂、防腐剂、糖精，不能代替水。",
//        "relativeContent": "",
//        "imgURL": $rawfile('feed_drinkItems_Beverage.png'),
//        "reserve": "3 M",
//        "isVisible": true,
//        "price": 10
//      }];
//  }